package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by L on 27.10.2016.
 */
public class CurrencyRepository {

    private Connection connection;

    public CurrencyRepository(Connection connection) {
        this.connection = connection;

        try {
            Statement createTable = connection.createStatement();
            String createTableSql = ""
                    + "CREATE TABLE currency("
                    + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "name varchar(5),"
                    + ")";
            createTable.executeUpdate(createTableSql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        return connection;
    }
}
