package dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by L on 27.10.2016.
 */
public class CurrencyRepository {

    private Connection connection;

    public CurrencyRepository(Connection connection) {
        this.connection = connection;

            String createTableSql = ""
                    + "CREATE TABLE currency("
                    + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "name varchar(5),"
                    + ")";
        Statement createTable;
    
    try {
    	createTable = connection.createStatement();
    	
    	boolean tableExists = false;
    	
    	ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
        
        while(rs.next()){
        	if(rs.getString("Table_Name").equalsIgnoreCase("currency")){
        		tableExists = true;
        		break;
        	}
        }
        if(!tableExists)
        	createTable.executeUpdate(createTableSql);
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    public Connection getConnection() {
        return connection;
    }
}
