package dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by L on 27.10.2016.
 */
public class CurrencyRepository extends RepositoryBase{


    public CurrencyRepository(Connection connection) {
        super(connection);
    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE currency("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "name varchar(5)," + ")";
    }

    @Override
    protected String tableName() {
        return "currency";
    }
}
