package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.History;

import java.sql.Connection;
import java.sql.SQLException;

public class HistoryRepository extends RepositoryBase<History> {


    public HistoryRepository(Connection connection,
			IMapResultSetIntoEntity<History> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE history("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "date DATE,"
                + "amount DECIMAL,"
                + "rate DOUBLE,"
                + "WALLET_FROM_ID int,"
                + "WALLTET_TO_ID int,"
                + "OPERATION_ID int,"
                + "FOREIGN KEY (WALLET_FROM_ID) REFERENCES wallet(id),"
                + "FOREIGN KEY (WALLTET_TO_ID) REFERENCES wallet(id),"
                + "FOREIGN KEY (OPERATION_ID) REFERENCES operations(id)"
                + ")";
    }

    @Override
    protected String tableName() {
        return "History";

    }

    @Override
    protected String insertSql() {
        return "INSERT INTO history("
                + "date, amount, rate,"
                + " WALLET_FROM_ID,"
                + " WALLTET_TO_ID,"
                + "OPERATION_ID"
                + ") VALUES (?,?,?,?,?,?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE HISTORY SET (date, amount, rate, WALLET_FROM_ID" +
                ", WALLET_TO_ID, OPERATION_ID)= (?,?,?,?,?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(History history) throws SQLException {
        update.setDate(1, history.getDate());
        update.setFloat(2, history.getAmount());
        update.setDouble(3, history.getRate());
        update.setInt(4, history.getFromWalletId());
        update.setInt(5, history.getToWalletId());

    }

    @Override
    protected void setInsert(History history) throws SQLException {
        insert.setDate(1, history.getDate());
        insert.setDouble(2, history.getAmount());
        insert.setDouble(3, history.getRate());
        insert.setInt(4, history.getFromWalletId());
        insert.setInt(5, history.getToWalletId());
    }
}
