package dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by L on 05.11.2016.
 */
public class OperationRepository {

    private Connection connection;

    private String createTableSql = ""
            + "CREATE TABLE operations("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "name varchar(5),"
            + ")";

    private Statement createTable;

    public OperationRepository(Connection connection) {
        this.connection = connection;


        try {
            createTable = connection.createStatement();
            boolean tableExists = false;
            ResultSet resultSet = connection.getMetaData().getTables(null, null, null, null);

            while (resultSet.next()) {
                if (resultSet.getString("Table_Name").equalsIgnoreCase("operations")) {
                    tableExists = true;
                    break;
                }
            }
            if (!tableExists) {
                createTable.executeUpdate(createTableSql);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        return connection;
    }
}

