package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Person;

public class PersonRepository extends RepositoryBase<Person> {

	public PersonRepository(Connection connection,
			IMapResultSetIntoEntity<Person> mapper, IUnitOfWork uow) {
		super(connection,mapper, uow);
	}
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE people("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "people";
	}

	protected String insertSql() {
		return "INSERT INTO people(name, surname) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE people SET (name, surname)=(?,?) WHERE id=?";
	}


	@Override
	protected void setUpdate(Person entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		
	}

	@Override
	protected void setInsert(Person entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
	}
	
}
