package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by L on 05.11.2016.
 */
public class WalletRepository {

    private Connection connection;

    public WalletRepository(Connection connection) {
        this.connection = connection;

        try {
            Statement createTable = connection.createStatement();
            String createTableSql = ""
                    + "CREATE TABLE wallet("
                    + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                    + "accountId int,"
                    + "asset DECIMAL,"
                    + "CURRENCY_ID int,"
                    + "PERSON_ID int,"
                    + "FOREIGN KEY (PERSON_ID) REFERENCES people(id),"
                    + "FOREIGN KEY (CURRENCY_ID) REFERENCES currency(id)"
                    + ")";
            createTable.executeUpdate(createTableSql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        return connection;
    }
}